[package]
name = "texpresso_protocol"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "^1.0.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
cpu-time = "1.0"
